#!/usr/bin/env bash

log () {
  local MESSAGE=
  local SECTIONS=
  local SEVERITY=
  local LEVEL=1
  local LEVEL_SET=0
  local NAME="${LOG_NAME:-$0}"

  LOG_THRESHOLD=${LOG_THRESHOLD:-1}

  while [[ $# -gt 0 ]]; do
    case $1 in
      -n) NAME="$2" && shift ;;
      -e) SEVERITY='[ERROR]' && LEVEL=4 && LEVEL_SET=1 ;;
      -w) SEVERITY='[WARN]' && LEVEL=3 && LEVEL_SET=1 ;;
      -i) SEVERITY='[INFO]' && LEVEL=2 && LEVEL_SET=1 ;;
      -d) SEVERITY='[DEBUG]' && LEVEL=0 && LEVEL_SET=1 ;;
      -s|--severity) SEVERITY="$2" && shift ;;
      .*) SECTIONS="${SECTIONS:-}$1" ;;
      *) MESSAGE="$*" && shift $(( $# - 1 )) ;;
    esac
    shift
    if [[ $LEVEL_SET -gt 0 ]]; then
      LEVEL_SET=0
      if [[ $LEVEL -lt $LOG_THRESHOLD ]] && [[ -z ${DEBUG-} ]]; then
        return
      fi
    fi
  done

  if [[ $LEVEL -ge 4 ]]; then
    printf '%s\n' "${SEVERITY:+$SEVERITY }(${NAME}${SECTIONS})${MESSAGE:+ $MESSAGE}" >&2
  else
    printf '%s\n' "${SEVERITY:+$SEVERITY }(${NAME}${SECTIONS})${MESSAGE:+ $MESSAGE}"
  fi
}

