#!/usr/bin/env bash

log () {
  local MESSAGE=
  local SECTIONS=
  local SEVERITY=
  local LEVEL=1
  local LEVEL_SET=0
  local FILE="${0##*/}"
  local STEM="${FILE%.*}"
  local TITLE="${LOG_NAME:-$STEM}"
  local USE_STDOUT=0

  LOG_THRESHOLD=${LOG_THRESHOLD:-1}

  while [[ $# -gt 0 ]]; do
    case $1 in
      -t) TITLE="$2" && shift ;;
      -e) SEVERITY='[ERROR]' && LEVEL=4 && LEVEL_SET=1 ;;
      -w) SEVERITY='[WARN]' && LEVEL=3 && LEVEL_SET=1 ;;
      -i) SEVERITY='[INFO]' && LEVEL=2 && LEVEL_SET=1 ;;
      -n) SEVERITY='[NOTE]' && LEVEL=1 && LEVEL_SET=1 ;;
      -d) SEVERITY='[DEBUG]' && LEVEL=0 && LEVEL_SET=1 ;;
      -s|--severity) SEVERITY="$2" && shift ;;
      -o) USE_STDOUT=1 ;;
      .*|:*) SECTIONS="${SECTIONS:-}$1" ;;
      *) MESSAGE="$*" && shift $(( $# - 1 )) ;;
    esac
    shift
    if [[ $LEVEL_SET -gt 0 ]]; then
      LEVEL_SET=0
      if [[ $LEVEL -lt $LOG_THRESHOLD ]] && [[ -z ${DEBUG-} ]]; then
        return
      fi
    fi
  done

  if [[ $USE_STDOUT -gt 0 ]]; then
    printf '%s\n' "${SEVERITY:+$SEVERITY }(${TITLE}${SECTIONS})${MESSAGE:+ $MESSAGE}"
  else
    printf '%s\n' "${SEVERITY:+$SEVERITY }(${TITLE}${SECTIONS})${MESSAGE:+ $MESSAGE}" >&2
  fi
}

