#!/usr/bin/env bash

[[ -n "$LOG_NAME" ]] || LOG_NAME="reconfigure"
. "$PORTABLES"/log
export log

THIS="$(realpath "$0" 2>/dev/null || command -v "$0")"
HERE="$(dirname "$THIS")"

if [[ $# -gt 0 ]]; then
  for tool in $@; do
    sh "${HERE}/machine-tools/${tool}.sh" config
  done
else
  for tool_script in "$HERE"/machine-tools/*.sh; do
    sh "$tool_script" config
  done
fi
