#! /usr/bin/env zsh

# load named directories into hash table
[[ -e ~/.named-dirs.zsh ]] && . ~/.named-dirs.zsh

# path shortening
abrvdir=${(D)${~1}}

if (( $#abrvdir > 16 )); then
  if (( ${#${(s:/:)abbrvdir}} == 2 )); then
    print "$abrvdir"
    exit
  fi
  print "${abrvdir%%/*}/…/${abrvdir##*/}"
  exit
fi

print "$abrvdir"

# bash-friendly snippet if I ever decide to implement a fallback
# sed -E "s@^$HOME@~@; s@([^/])[^/]*/@\1/@g" <<< $1

