#! /bin/zsh

: ${HOME:=~}
: ${ZSH_CUSTOM:="${ZSH:="${HOME}/.oh-my-zsh"}/custom"}
MACHINE=${${HOST%%.*}:-${(%):-%m}}

OLD_PWD="$PWD"
cd "$PORTABLES"

# links into home directory
homedirdots=(
  .$MACHINE.env.zsh
  .zprofile
  .precompinit.zsh
  .p10k.zsh
  .vimrc
  .editorconfig
  .config/**/*(.N)
  Library/**/*(.N)
)

for f in "${homedirdots[@]}"; do
  mkdir -p "$HOME/$f:h"
  ln -f {,"$HOME/"}"$f"
done

ln -f {omz+,"$HOME"/}.zshrc

# links into omz custom directory
[[ "$ZSH_THEME" == **p*10k** ]] \
&& ln -f {.,"$ZSH_CUSTOM"/}p10k.zsh

ln -f .aliases "$ZSH_CUSTOM"/aliases.zsh
ln -f {.,"$ZSH_CUSTOM"/zz_}andfinally.zsh

cd "$OLD_PWD"

[[ "$1" = '-q' ]] || print 'Now run `exec zsh`'
