#!/usr/bin/env bash

export LOG_NAME="reinstantiate"
/usr/bin/env bash "$PORTABLES"/instantiate
unset LOG_NAME
read -k '?Would you like to replace the shell now? [Y|n] '
if [[ ! "$REPLY" = n ]]; then
  echo 'Replacing shell, please wait…'
  exec $SHELL
fi
