#!/usr/bin/env bash

export LOG_NAME="retune"
/usr/bin/env bash "$PORTABLES"/reconfigure $@
unset LOG_NAME
read -qk '?Would you like to replace the shell? [Y|n] '
if [[ ! "$REPLY" = n ]]; then
  echo 'Replacing shell, please wait…'
  exec $SHELL
fi
