#! /usr/bin/env zsh

# load named directories into hash table
[[ -e ~/.named-dirs.zsh ]] && . ~/.named-dirs.zsh

# path shortening
abrvdir=${(D)${~1}}
dirarry=("${(@s:/:)${abrvdir}}")

if (( $#dirarry <= 3 )); then
  print "$abrvdir"
  exit
fi
print "${dirarry[1]}/…/${(j:/:)dirarry[-2,-1]}"
exit

# bash-friendly snippet if I ever decide to implement a fallback
# sed -E "s@^$HOME@~@; s@([^/])[^/]*/@\1/@g" <<< $1

