#! /bin/zsh

: ${HOME:=~}
: ${ZSH_CUSTOM:=${ZSH:=$HOME/.oh-my-zsh}/custom}
MACHINE=${${HOST%%.*}:-${(%):-%m}}

# links into home directory
homedirdots=(.zprofile .precompinit.zsh .vimrc .config/git/ignore)

for f in $homedirdots; do
  ln -f {$PORTABLES,$HOME}/$f
done

# links into omz custom directory
ln -f $PORTABLES/.aliases $ZSH_CUSTOM/aliases.zsh
ln -f {$PORTABLES/.$MACHINE.,$ZSH_CUSTOM/00_}env.zsh
ln -f {$PORTABLES/.,$ZSH_CUSTOM/}p10k.zsh
ln -f {$PORTABLES/.,$ZSH_CUSTOM/zz_}andfinally.zsh

ln -f {$PORTABLES/omz+,$HOME/}.zshrc

[[ $1 = '-q' ]] || print 'Now run `exec zsh`'