format = "$all$fill $status$battery$line_break$character"

[aws]
  symbol = " "

[buf]
  symbol = " "

[bun]
  symbol = " "

[c]
  symbol = " "

[cpp]
  symbol = " "

[cmake]
  symbol = " "

[conda]
  symbol = " "

[crystal]
  symbol = " "

[dart]
  symbol = " "

[deno]
  symbol = " "

[directory]
  # fish_style_pwd_dir_length = 3
  read_only = " 󰌾"

[direnv]
  disabled = false
  symbol   = "󱨉 "

[docker_context]
  symbol = " "

[elixir]
  symbol = " "

[elm]
  symbol = " "

[fennel]
  symbol = " "

[fill]
  style  = "black"
  symbol = "·"

[fossil_branch]
  symbol = " "

[gcloud]
  format = 'on [$symbol$active(:$project)(\($region\))]($style) '
  symbol = "󰊭 "
  [gcloud.project_aliases]
    sunlit-alloy-444818-j2 = 'sunlit-alloy'

[git_branch]
  symbol = " "

[git_commit]
  tag_symbol = '  '

[git_status]
  format = '([$all_status$ahead_behind]($style) )'

[golang]
  symbol = " "

[guix_shell]
  symbol = " "

[haskell]
  symbol = " "

[haxe]
  symbol = " "

[hg_branch]
  symbol = " "

[hostname]
  ssh_symbol = " "

[java]
  symbol = " "

[julia]
  symbol = " "

[kotlin]
  symbol = " "

[lua]
  symbol = " "

[memory_usage]
  symbol = "󰍛 "

[meson]
  symbol = "󰔷 "

[nim]
  symbol = "󰆥 "

[nix_shell]
  symbol = " "

[nodejs]
  symbol = " "

[ocaml]
  symbol = " "

[os.symbols]
  AlmaLinux        = " "
  Alpaquita        = " "
  Alpine           = " "
  Amazon           = " "
  Android          = " "
  Arch             = " "
  Artix            = " "
  CachyOS          = " "
  CentOS           = " "
  Debian           = " "
  DragonFly        = " "
  Emscripten       = " "
  EndeavourOS      = " "
  Fedora           = " "
  FreeBSD          = " "
  Garuda           = "󰛓 "
  Gentoo           = " "
  HardenedBSD      = "󰞌 "
  Illumos          = "󰈸 "
  Kali             = " "
  Linux            = " "
  Mabox            = " "
  Macos            = " "
  Manjaro          = " "
  Mariner          = " "
  MidnightBSD      = " "
  Mint             = " "
  NetBSD           = " "
  NixOS            = " "
  Nobara           = " "
  OpenBSD          = "󰈺 "
  OracleLinux      = "󰌷 "
  Pop              = " "
  Raspbian         = " "
  RedHatEnterprise = " "
  Redhat           = " "
  Redox            = "󰀘 "
  RockyLinux       = " "
  SUSE             = " "
  Solus            = "󰠳 "
  Ubuntu           = " "
  Unknown          = " "
  Void             = " "
  Windows          = "󰍲 "
  openSUSE         = " "

[package]
  symbol = "󰏗 "

[perl]
  symbol = " "

[php]
  symbol = " "

[pijul_channel]
  symbol = " "

[pixi]
  symbol = "󰏗 "

[python]
  symbol = "󰌠 "

[rlang]
  symbol = "󰟔 "

[ruby]
  symbol = " "

[rust]
  symbol = "󱘗 "

[scala]
  symbol = " "

[status]
  disabled   = false
  format     = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
  map_symbol = true
  pipestatus = true
  symbol     = '✘ '

[swift]
  symbol = " "

[terraform]
  symbol = "󱁢 "

[zig]
  symbol = " "

[gradle]
  symbol = " "
